services:
  elasticsearch:
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - node.name=snowstorm
      - cluster.name=snowstorm-cluster
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - ./data:/usr/share/elasticsearch/data
#    networks:
#      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 1s
      timeout: 1s
      retries: 60
    ports:
      - 127.0.0.1:9200:9200
    mem_reservation: 5g

  snowstorm:
    restart: unless-stopped
    image: snomedinternational/snowstorm:latest
    container_name: snowstorm
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: java -Xms2g -Xmx4g --add-opens java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -cp @/app/jib-classpath-file org.snomed.snowstorm.SnowstormApplication --elasticsearch.urls=http://elasticsearch:9200 --codesystem.all.latest-version.allow-future=true
#    networks:
#      - elastic
#      - termx
    ports:
      - 8080:8080


  browser:
    image: snomedinternational/snomedct-browser:latest
    #image: docker.kodality.com/snomedct-browser:latest
    container_name: browser
    depends_on:
      - snowstorm
    links:
      - snowstorm:snowstorm
#    networks:
#      - elastic
    environment:
      - API_HOST=http://snowstorm:8080/
    ports:
      - 9000:80
    restart: always

#networks:
# elastic:
# termx:
#   name: termxnet
#    external: true

